#version 430 compatibility
#extension GL_ARB_COMPUTE_SHADER : enable
#extension GL_ARB_SHADER_STORAGE_BUFFER_OBJECT : enable

struct ParticleData
{
	mat4 mModel;
	vec4 more_data;
};

layout(std430, binding = 3) buffer ModelBlock
{
	ParticleData data[];
};

layout(local_size_x = 128, local_size_y = 1, local_size_z = 1) in;

void main()
{
	uint gid = gl_GlobalInvocationID.x;

	data[gid].mModel = mat4(0.0f);
	data[gid].more_data = vec4(0.0f);
}